// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt7ap9aNhbeKSpcH6tvLjJaS6eAjRrwdI',
    appId: '1:498573788944:web:a137dde89fd0936d364795',
    messagingSenderId: '498573788944',
    projectId: 'currensee-cec5b',
    authDomain: 'currensee-cec5b.firebaseapp.com',
    storageBucket: 'currensee-cec5b.firebasestorage.app',
    measurementId: 'G-5BE1BEP54S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAOw6vzEFk7TYZGW1JMsVnqT_QwK8N49w',
    appId: '1:498573788944:android:6d526647c55ba946364795',
    messagingSenderId: '498573788944',
    projectId: 'currensee-cec5b',
    storageBucket: 'currensee-cec5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIP-_YiMb23ApOeuQPbBvR33g1AtD0Ccw',
    appId: '1:498573788944:ios:9ac240c84dc0945b364795',
    messagingSenderId: '498573788944',
    projectId: 'currensee-cec5b',
    storageBucket: 'currensee-cec5b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIP-_YiMb23ApOeuQPbBvR33g1AtD0Ccw',
    appId: '1:498573788944:ios:9ac240c84dc0945b364795',
    messagingSenderId: '498573788944',
    projectId: 'currensee-cec5b',
    storageBucket: 'currensee-cec5b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt7ap9aNhbeKSpcH6tvLjJaS6eAjRrwdI',
    appId: '1:498573788944:web:d09c46ebfb9d04c7364795',
    messagingSenderId: '498573788944',
    projectId: 'currensee-cec5b',
    authDomain: 'currensee-cec5b.firebaseapp.com',
    storageBucket: 'currensee-cec5b.firebasestorage.app',
    measurementId: 'G-30NRQ66LR8',
  );
}
